/// Data structure that represent an Haskell function signature:
/// {fn_name} :: {fn_type[0]} -> {fn_type[1]} -> ... -> {fn_type[n-1]}
pub(crate) struct Signature {
    pub(crate) fn_name: String,
    pub(crate) fn_type: Vec<String>,
}

impl std::fmt::Display for Signature {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_fmt(format_args!(
            "{} :: {}",
            self.fn_name,
            self.fn_type.join(" -> ")
        ))?;
        Ok(())
    }
}

/// Produce the content of `lib/{module}.hs` given a list of Signature
pub(crate) fn template(module: &str, signatures: &[Signature]) -> String {
    let names = get_names(signatures);
    let imports = get_imports(signatures);
    format!(
        "-- This file was generated by `hs-bindgen` crate and contain C FFI bindings
-- wrappers for every Rust function annotated with `#[hs_bindgen]`

{{-# LANGUAGE ForeignFunctionInterface #-}}

-- Why not rather using `{{-# LANGUAGE CApiFFI #-}}` language extension?
--
-- * Because it's GHC specific and not part of the Haskell standard:
--   https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/ffi.html ;
--
-- * Because the capabilities it gave (by rather works on top of symbols of a C
--   header file) can't work in our case. Maybe we want a future with an
--   {{-# LANGUAGE RustApiFFI #-}} language extension that would enable us to
--   work on top of a `.rs` source file (or a `.rlib`, but this is unlikely as
--   this format has purposely no public specifications).

module {module} ({names}) where

import Foreign.C.String

{imports}"
    )
}

fn get_names(signatures: &[Signature]) -> String {
    signatures
        .iter()
        .map(|x| x.fn_name.clone())
        .collect::<Vec<String>>()
        .join(" ")
}

fn get_imports(signatures: &[Signature]) -> String {
    signatures
        .iter()
        .map(|sig| format!("foreign import ccall unsafe \"c_{}\" {sig}", sig.fn_name))
        .collect::<Vec<String>>()
        .join("\n")
}
